### PR TITLE
Adding a visual guide for interaction with the webapp

### PR DESCRIPTION
**Pull request by ContonJon**

### CODE REVIEW

**Comment by lilygostovic** [comment]
@ContonJon what do you want to do with this PR? I think it would be nice to have but maybe should we move it to another page? I think it may be too crowded on the home page... Or if we could make it smaller somehow?

**Comment by lilygostovic** [comment]
> @ContonJon what do you want to do with this PR? I think it would be nice to have but maybe should we move it to another page? I think it may be too crowded on the home page... Or if we could make it smaller somehow?

Also we'll need to update the images too to match the new changes

**Comment by ContonJon** [comment]
> @ContonJon what do you want to do with this PR? I think it would be nice to have but maybe should we move it to another page? I think it may be too crowded on the home page... Or if we could make it smaller somehow?

The idea was to have a visual guide, which was something Kristin mentioned at some point. For the sake of increased usability. Somehow I feel like creating an entire new page would make it too "hidden" away from the user. I think making it more concise or smaller would be better? If possible.

**Comment by ContonJon** [comment]
#

> > @ContonJon what do you want to do with this PR? I think it would be nice to have but maybe should we move it to another page? I think it may be too crowded on the home page... Or if we could make it smaller somehow?
> 
> Also we'll need to update the images too to match the new changes

Yes, I was planning on doing this first thing tomorrow (june 1)

**Comment by ContonJon** [comment]
> > @ContonJon what do you want to do with this PR? I think it would be nice to have but maybe should we move it to another page? I think it may be too crowded on the home page... Or if we could make it smaller somehow?
> 
> The idea was to have a visual guide, which was something Kristin mentioned at some point. For the sake of increased usability. Somehow I feel like creating an entire new page would make it too "hidden" away from the user. I think making it more concise or smaller would be better? If possible.

I may have found a way to make it smaller

**Comment by lilygostovic** [comment]
This looks super great!!! Sorry it took me so long to merge...

**Review by lilygostovic — APPROVED** [review]

**Pull request merged**
